version: '2'
services:
  plex:
    restart: unless-stopped
    image: sashgorokhov/plex
    network_mode: "host"
    volumes:
      - "/mnt/plex:/usr/sbin/plexmediaserver"
      - "/mnt/media:/media"
    ports:
      - "0.0.0.0:32400:32400"
  deluge:
    restart: unless-stopped
    image: sashgorokhov/deluge
    ports:
      - "8112:8112"
      - "127.0.0.1:58846:58846"
    volumes:
      - "/mnt/media:/media"
  webdav:
    restart: unless-stopped
    image: sashgorokhov/webdav
    ports:
      - "8080:80"
    volumes:
      - "/mnt/media:/media"
    environment:
      USERNAME:
      PASSWORD: